### ISSUE TITLE
When will logs get dropped by this plugin?

### ISSUE THREAD

**Issue by Bryji** [SumoLogic/sumologic-docker-logging-driver#16]
Hi,
This plugin looks really interesting, I have a couple of questions regarding particular lines of code: 
https://github.com/SumoLogic/sumologic-docker-logging-driver/blob/7ef84d5cad7ee5185696713d4567c25f19c41275/logger.go#L115 
https://github.com/SumoLogic/sumologic-docker-logging-driver/blob/7ef84d5cad7ee5185696713d4567c25f19c41275/logger.go#L91

These lines seem to indicate circumstances in which logs will be lost (log too large to batch and batch full). Could you clarify the circumstances in which this would occur (not sure what exactly 'batch' is or what size it may be)?

Is anyone using this plugin in production?

Cheers!
Bryan

**Comment by bin3377** [comment]
There is a memory queue pile the message before sending and there is a parameter `sumo-queue-size` for tuning how large of data it can hold
