### ISSUE TITLE
configured logging driver does not support reading

### ISSUE THREAD

**Issue by komuw** [SumoLogic/sumologic-docker-logging-driver#17]
When this plugging is configured as the logging driver, reading logs (via `docker logs <container-id>`) returns an error:
```sh
Error response from daemon: configured logging driver does not support reading
```

It seems like you guys haven't implemented `LogDriver.ReadLogs`[1] capabilities. 
Do you intend to do so?

1. https://docs.docker.com/engine/extend/plugins_logging/#logdriverreadlogs

**Comment by komuw** [comment]
hi . anyone here??????

**Comment by yuting-liu** [comment]
Hi @komuw, we are not going to support ReadLogs API. Since we intended our plugin to only send logs to Sumo UI, not be capable of reading back locally.
If you have any questions about how to use Sumo plugin, please refer  (https://github.com/SumoLogic/sumologic-docker-logging-driver/blob/master/README.md) about how to use it then.

**Comment by komuw** [comment]
@yuting-liu Hi,
We are already using sumologic docker logging plugin. 
However when debugging an issue that has happened in our servers, it is essential to be able to stream logs locally to help in debugging. 

When you say `we are not going to support ReadLogs API` is definite position or would you accept pull requests if someone was to send one fixing this issue?

**Comment by yuting-liu** [comment]
@komuw Streaming logs locally is not an intended use case for the plugin. 

As you mentioned that it would be helpful to read logs programmatically for debugging, we have Search API java implementation (https://github.com/SumoLogic/sumo-java-client) and Livetail CLI: (https://github.com/SumoLogic/livetail-cli). You could see if these meet your requirements.

**Comment by komuw** [comment]
I beg to differ, but I'll let the matter lie.
