### ISSUE TITLE
Failed to log msg because of broken pipe

### ISSUE THREAD

**Issue by mdheeraj24** [SumoLogic/sumologic-docker-logging-driver#18]
Hi,
I am using this sumologic-docker-logger-driver plugin version 1.0.2 with following log options

        "sumo-queue-size": "1000",
        "sumo-batch-size": "20000000",
        "sumo-compress" : "true",
        "sumo-compress-level" : "5",
        "sumo-sending-interval" : "15",

The rate of injest of logs is : 6GB / minute.
Fd limit inside the container is set to 65000.

While doing so, getting the following error 
`
time="2018-04-23T13:00:07.118852858Z" level=error msg="Failed to log msg \"\" for logger sumologic: write /proc/self/fd/74: broken pipe"
`
Can you please help ?

**Comment by bin3377** [comment]
Looks like there is a similar issue reported - https://github.com/moby/moby/issues/36929
Could you please copy the result of `docker version`, `docker info` and the configuration you used?
