### ISSUE TITLE
docker-logging-driver plugin does not exist?

### ISSUE THREAD

**Issue by kevinwsin** [SumoLogic/sumologic-docker-logging-driver#22]
Hi, I just noticed that I am unable to pull the docker-logging-driver from several servers, though I was able to earlier today:

```
$ docker plugin install store/sumologic/docker-logging-driver:1.0.2 --alias sumologic --grant-all-permissions
Error response from daemon: pull access denied for store/sumologic/docker-logging-driver, repository does not exist or may require 'docker login'
```

Did something just happen?

**Comment by kevinrambaud** [comment]
I run into the same problem.

**Comment by bin3377** [comment]
Looking into this. So far looks like nothing changed from sumo side, contacting docker store

**Comment by bin3377** [comment]
Confirmed it's a docker store issue and it's resolved now. Close the ticket
