### ISSUE TITLE
sumo-sending-frequency does not actually exist.

### ISSUE THREAD

**Issue by pieterza** [SumoLogic/sumologic-docker-logging-driver#23]
`sumo-sending-frequency` referenced here, but does not exist in code.

https://github.com/SumoLogic/sumologic-docker-logging-driver#option-a-start-a-container-to-use-sumo-driver 

This should probably be changed to `sumo-sending-interval`

**Comment by samjsong** [comment]
Thanks for pointing this out. This has been fixed in https://github.com/SumoLogic/sumologic-docker-logging-driver/pull/25.
