### ISSUE TITLE
ETA on New release? [file already closed]

### ISSUE THREAD

**Issue by mlehner616** [SumoLogic/sumologic-docker-logging-driver#26]
Hello, I'm getting some impact by the "file already closed" issue. I see that a fix has been pushed to master but it's not published on dockerhub. Is there any ETA on that?

**Comment by mlehner616** [comment]
@samjsong

**Comment by samjsong** [comment]
Hello, we've published and re-certified an updated version of the [Sumo Logic Logging Plugin](https://hub.docker.com/plugins/sumologic-logging-plugin) on DockerHub. The new version number is `1.0.3`, and can be installed with
```
docker plugin install store/sumologic/docker-logging-driver:1.0.3 --alias sumologic --grant-all-permissions
```
Hope this helps! Please feel free to let us know if you have any further concerns.
