### ISSUE TITLE
Errors in the docker logs

### ISSUE THREAD

**Issue by machad** [SumoLogic/sumologic-docker-logging-driver#33]
We are using the sumologic docker logging driver with our docker containers in order to ship logs up to sumo. The logging driver works very well, but we've found a number of strange errors like the following in our syslog on the host:
	
Jun 19 01:12:05 ip-172-25-130-83 dockerd: time="2020-06-19T01:12:05Z" level=error msg="time=\"2020-06-19T01:12:05Z\" level=info msg=\"sumologic: Sending logs batch. batch-size: 126 bytes\"" plugin=48634abf754d3e0bd219aeb8af6d89b58aace92250d0375b17b45fa39ca16366

It seems the logging driver is printing an info message, and dockerd is picking it up and sending it along to syslog as an error, but we're at a loss as to where we can suppress these logs on the host side. We would prefer not to use a pre-processing rule to do this.

We have version 1.0.3 of the plugin and version 19.03.6-ce, build 369ce74 of docker.

**Comment by samjsong** [comment]
This has been fixed as of `1.0.4`. Thanks for bringing it to our attention!
