### ISSUE TITLE
Publish images to Amazon Public ECR

### ISSUE THREAD

**Issue by amartani** [SumoLogic/sumologic-docker-logging-driver#42]
DockerHub has been tightening enforcement of their image pull rate limits, which is impacting our usage of `sumologic/docker-logging-driver` docker image.

SumoLogic already provides several images via AWS Public ECR: https://gallery.ecr.aws/sumologic/

However, I wasn't able to find the docker-logging-driver among these. Would it be possible to publish these images to AWS Public ECR?

Thank you!

**Comment by yermulnik** [comment]
Just hit the same. Would appreciate having this image in AWS Public ECR.

**Comment by rnishtala-sumo** [comment]
Raised this PR: https://github.com/SumoLogic/sumologic-docker-logging-driver/pull/43

**Comment by rnishtala-sumo** [comment]
The images have been published here! - https://gallery.ecr.aws/sumologic/docker-logging-driver

**Comment by yermulnik** [comment]
Yay, thanks a bunch!
I'll hand this update over to our deployment team so that they can switch to AWS Public ECR now.
